# Generated by Django 3.2.9 on 2021-11-27 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CsvFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.FileField(upload_to='media')),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('identifier', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('issue_date', models.DateField()),
                ('total_amount', models.FloatField(default=0)),
                ('rating', models.IntegerField(default=1)),
                ('maturity_date', models.DateField()),
                ('total_expected_interest_amount', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='LoanCalc',
            fields=[
                ('loan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.loan')),
                ('invested_amount', models.FloatField()),
                ('investment_date', models.DateField()),
                ('expected_interest_amount', models.FloatField()),
                ('is_closed', models.BooleanField(default=False)),
                ('expected_irr', models.FloatField()),
                ('realized_irr', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='CashFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_date', models.DateField()),
                ('type', models.CharField(max_length=20)),
                ('amount', models.FloatField()),
                ('loan_identifier', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='cash_flows', to='api.loan')),
            ],
        ),
    ]
