# Generated by Django 3.2.9 on 2021-11-27 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_cashflow_loan_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashflow',
            name='loan_identifier',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='cash', to='api.loan'),
        ),
    ]
